<?php
return [
    "Allergologia",
    "Anatomia patologica",
    "Angiologia",
    "Chirurgia generale",
    "Chirurgia plastica",
    "Chirurgia vascolare",
    "Dermatologia",
    "Ematologia",
    "Gastroenterologia",
    "Genetica medica",
    "Geriatria",
    "Malattie infettive",
    "Medicina dello sport",
    "Medicina del lavoro",
    "Fisiatria",
    "Medicina generale",
    "Medicina legale",
    "Virologia",
    "Neonatologia",
    "Neurochirurgia",
    "Neurologia",
    "Oftalmologia",
    "Oncologia",
    "Ortopedia",
    "Ginecologia",
    "Pediatria",
    "Psichiatria",
    "Radiodiagnostica",
    "Radioterapia",
    "Reumatologia",
    "Urologia",
];
